---
- name: Clone PokedashAAC from Github
  git:
    repo: https://github.com/ImmortalDisorderOT/pokedash-website.git
    dest: /home/otsmanager/www/public_html/pokedash
  become: true
  become_user: otsmanager

- name: Configure SQL username
  lineinfile:
    dest: /home/otsmanager/www/public_html/pokedash/config.php
    regexp: \$config\['sqlUser'\]
    line: "        $config['sqlUser'] = 'pokedash';"

- name: Configure SQL password
  lineinfile:
    dest: /home/otsmanager/www/public_html/pokedash/config.php
    regexp: \$config\['sqlPassword'\]
    line: "        $config['sqlPassword'] = '{{mysql_pokedash_pass}}';"

- name: Configure SQL database
  lineinfile:
    dest: /home/otsmanager/www/public_html/pokedash/config.php
    regexp: \$config\['sqlDatabase'\]
    line: "        $config['sqlDatabase'] = 'pokedash';"

- name: Configure SQL host
  lineinfile:
    dest: /home/otsmanager/www/public_html/pokedash/config.php
    regexp: \$config\['sqlHost'\]
    line: "        $config['sqlHost'] = 'localhost';"

- name: Configure server path
  lineinfile:
    dest: /home/otsmanager/www/public_html/pokedash/config.php
    regexp: \$config\['server_path'\]
    line: "        $config['server_path'] = '/home/otsmanager/pokedash';"

- name: Import PokedashAAC database schema
  mysql_db:
    name: pokedash
    state: import
    target: /home/otsmanager/www/public_html/pokedash/engine/database/znote_schema.sql
